[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/api/*"
  to = "https://omartejada.com/contenido/wp-json/wp/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp-json/*"
  to = "https://omartejada.com/contenido/wp-json/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración para funciones serverless
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
